# Define all test suites in this file here (by adding a new section).

# [test_suite_name]: The name of your test suite. Use this exact name on the
#   command line when running cli.py suite:run [test_suite_name]. Do not replace
#   "_" with "-".
# base_dir: The directory inside the ray repository, in which to operate. Files
#   used in `exec_cmd` (e.g. run.sh) should be located here.
# cluster_config: The path+filename of the cluster yaml config to use to bring
#   up a ray cluster. The path is relative to the `base_dir` above.
# exec_cmd: The actual command to run (on the created cluster).

# ---------------------------------------------------
# Regular job
# --------------------------------------------------
[microbenchmark]
base_dir = "release/microbenchmark"
cluster_config = "cluster.yaml"
exec_cmd = """
bash run.sh --ray-version={{ctx["ray_version"]}} \
            --commit={{ctx["git_commit"]}} \
            --ray-branch={{ctx["git_branch"]}}
"""

# ---------------------------------------------------
# Release tests.
# --------------------------------------------------
# [long_running_tests]
# base_dir = "ci/long_running_tests"
# cluster_config = "ray-project/cluster.yaml"
# exec_cmd = """
# bash run.sh --ray-version={{ctx["ray_version"]}} \
#             --commit={{ctx["git_commit"]}} \
#             --ray-branch={{ctx["git_branch"]}} \
#             --workload={{ctx["workload"]}}
# """

#     [[long_running_tests.case]]
#     workload = "serve"

#     [[long_running_tests.case]]
#     workload = "serve_failure"

#     [[long_running_tests.case]]
#     workload = "many_tasks"

[long_running_distributed]
base_dir = "release/long_running_distributed_tests"
cluster_config = "cluster.yaml"
exec_cmd = """
bash run.sh --ray-version={{ctx["ray_version"]}} \
            --commit={{ctx["git_commit"]}} \
            --ray-branch={{ctx["git_branch"]}} \
            --workload={{ctx["workload"]}}
"""

    [[long_running_distributed.case]]
    workload = "pytorch_pbt_failure"

    [[long_running_distributed.case]]
    workload = "horovod_test"


# ---------------------------------------------------
# Serve tests.
# --------------------------------------------------
# [serve]
# base_dir = "python/ray/serve/benchmarks"
# cluster_config = "single.yaml"
# exec_cmd = """
# python {{ctx["workload"]}}.py
# """
#     [[serve.case]]
#     workload = "handle"

#     [[serve.case]]
#     workload = "microbenchmark"

# [serve_cluster]
# base_dir = "python/ray/serve/benchmarks"
# cluster_config = "cluster.yaml"
# exec_cmd = """
# python scalability.py
# """


# ---------------------------------------------------
# RLlib tests.
# ---------------------------------------------------
[rllib_regression_tests]
base_dir = "release/rllib_tests/regression_tests"
cluster_config = "cluster.yaml"
exec_cmd = """
bash run.sh --ray-version={{ctx["ray_version"]}} \
            --commit={{ctx["git_commit"]}} \
            --ray-branch={{ctx["git_branch"]}}
"""

[rllib_stress_tests]
base_dir = "release/rllib_tests/stress_tests"
cluster_config = "cluster.yaml"
exec_cmd = """
bash run.sh --ray-version={{ctx["ray_version"]}} \
            --commit={{ctx["git_commit"]}} \
            --ray-branch={{ctx["git_branch"]}}
"""

[rllib_unit_gpu_tests]
base_dir = "release/rllib_tests/unit_gpu_tests"
cluster_config = "cluster.yaml"
exec_cmd = """
bash run.sh --ray-version={{ctx["ray_version"]}} \
            --commit={{ctx["git_commit"]}} \
            --ray-branch={{ctx["git_branch"]}}
"""
