[microbenchmark]
base_dir = "ci/microbenchmark"
cluster_config = "ray-project/cluster.yaml"
exec_cmd = """
bash run.sh --ray-version={{ctx["ray_version"]}} \
            --commit={{ctx["git_commit"]}} \
            --ray-branch={{ctx["git_branch"]}}
"""

[long_running_tests]
base_dir = "ci/long_running_tests"
cluster_config = "ray-project/cluster.yaml"
exec_cmd = """
bash run.sh --ray-version={{ctx["ray_version"]}} \
            --commit={{ctx["git_commit"]}} \
            --ray-branch={{ctx["git_branch"]}} \
            --workload={{ctx["workload"]}}
"""

    [[long_running_tests.case]]
    workload = "serve"

    [[long_running_tests.case]]
    workload = "many_tasks"
