steps:
  - label: Run xgboost_tests
    commands:
      - pip install -q -r requirements.txt
      - git clone -b release-automation https://github.com/krfricke/ray.git ~/ray
      - python e2e.py --test-config ~/ray/release/xgboost_tests/xgboost_tests.yaml --test-name tune_small
    env:
      ANYSCALE_CLOUD_ID: cld_4F7k8814aZzGG8TNUGPKnc
      ANYSCALE_PROJECT: prj_2xR6uT6t7jJuu1aCwWMsle # e2e-tests in release-automation@
      RELEASE_AWS_BUCKET: ray-release-test-results
      RELEASE_AWS_LOCATION: dev
      RELEASE_AWS_DB_NAME: ray_ci
      RELEASE_AWS_DB_TABLE: release_test_result
      AWS_REGION: us-west-2
    agents:
      queue: runner_queue_branch
    plugins:
      - docker#v3.8.0:
          image: "rayproject/ray"
          propagate-environment: true