setup: &setup
  env:
    ANYSCALE_CLOUD_ID: cld_4F7k8814aZzGG8TNUGPKnc
    ANYSCALE_PROJECT: prj_2xR6uT6t7jJuu1aCwWMsle # e2e-tests in release-automation@
    RELEASE_AWS_BUCKET: ray-release-automation-results
    RELEASE_AWS_LOCATION: dev
    RELEASE_AWS_DB_NAME: ray_ci
    RELEASE_AWS_DB_TABLE: release_test_result
    AWS_REGION: us-west-2
  agents:
    queue: runner_queue_branch
  plugins:
    - docker#v3.8.0:
        image: "rayproject/ray"
        propagate-environment: true

nightly: &nightly
  if: build.message =~ /Nightly/

weekly: &weekly
  if: build.message =~ /Weekly/



steps:
  - label: Run microbenchmark
    <<: *setup
    <<: *nightly
    commands:
      - pip install -q -r requirements.txt
      - pip install -U boto3 botocore
      - git clone -b ${RAY_BRANCH} https://github.com/ray-project/ray.git ~/ray
      - python e2e.py --test-config ~/ray/release/microbenchmark/microbenchmark.yaml --test-name microbenchmark --ray-branch ${RAY_BRANCH} --category ${RAY_BRANCH}



  # XGBoost tests
  - label: Run xgboost test train_small
    <<: *setup
    <<: *nightly
    commands:
      - pip install -q -r requirements.txt
      - pip install -U boto3 botocore
      - git clone -b ${RAY_BRANCH} https://github.com/ray-project/ray.git ~/ray
      - python e2e.py --test-config ~/ray/release/xgboost_tests/xgboost_tests.yaml --test-name tune_small --ray-branch ${RAY_BRANCH} --category ${RAY_BRANCH}

  - label: Run xgboost test tune_small
    <<: *setup
    <<: *nightly
    commands:
      - pip install -q -r requirements.txt
      - pip install -U boto3 botocore
      - git clone -b ${RAY_BRANCH} https://github.com/ray-project/ray.git ~/ray
      - python e2e.py --test-config ~/ray/release/xgboost_tests/xgboost_tests.yaml --test-name tune_small --ray-branch ${RAY_BRANCH} --category ${RAY_BRANCH}


  # Data processing tests
  - label: Run nightly test shuffle_10gb
    <<: *setup
    <<: *nightly
    commands:
      - pip install -q -r requirements.txt
      - pip install -U boto3 botocore
      - git clone -b ${RAY_BRANCH} https://github.com/ray-project/ray.git ~/ray
      - python e2e.py --test-config ~/ray/release/nightly_tests/nightly_tests.yaml --test-name shuffle_10gb --ray-branch ${RAY_BRANCH} --category ${RAY_BRANCH}
