name: daily-job

on:
  # push:
  #   branches: [ master ]
  schedule:
    #  Everyday
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - microbenchmark
          - serve
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run test suite
      env:
        ANYSCALE_CLI_TOKEN: ${{ secrets.ANYSCALE_CLI_TOKEN }}
        TEST_SUITE: ${{ matrix.suite }}
      run: |
        python cli.py suite:run ${TEST_SUITE}
