name: long-running-tests

on: {}
  # push:
  #   branches: [ master ]
  # schedule:
  #   # Every Monday
  #   - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
          - serve
          - serve_failure
          - many_tasks
          - actor_deaths
          - apex
          - impala
          - many_actor_tasks
          - many_drivers
          - many_ppo
          - many_tasks_serialized_ids
          - node_failures
          - pbt
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run test suite
      env:
        ANYSCALE_HOST: https://anyscale.dev
        ANYSCALE_CLI_TOKEN: ${{ secrets.ANYSCALE_CLI_TOKEN }}
        TEST_SUITE: ${{ matrix.suite }}
      run: |
        python cli.py suite:run long_running_tests-${TEST_SUITE} --no-wait
