name: long-running-tests

on:
  # push:
  #   branches: [ master ]
  schedule:
    # Every Monday
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run test suite
      env:
        ANYSCALE_HOST: https://anyscale.dev
        ANYSCALE_CLI_TOKEN: ${{ secrets.ANYSCALE_CLI_TOKEN }}
      run: |
        python cli.py suite:run long_running_tests --no-wait
