name: long-running-tests

on:
  push:
    branches: [ master ]
#   schedule:
#     - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
          - serve
          - serve_failure
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run test suite
      env:
        ANYSCALE_HOST: https://anyscale.dev
        ANYSCALE_CLI_TOKEN: ${{ secrets.ANYSCALE_CLI_TOKEN }}
        TEST_SUITE: ${{ matrix.suite }}
      run: |
        python cli.py --git-commit 39e809fa03aadd2b883c9098f87342a428550b35  suite:run long_running_tests-${TEST_SUITE}
